language: go
go:
  - 1.7.x
  - tip
services:
  - redis-server
env:
  - GAE=.go_appengine
  - GAE=
cache:
  directories:
    - vendor
    - glide-$(go version | awk '{ print $NF }' | tr '/' '-')
    - .go_appengine
install:
  - make installdeps
script:
  - make test
