language: go
go:
  - 1.7.x
  - tip
services:
  - redis-server
env:
  - BACKEND=aws CACHE=redis
  - BACKEND=aws CACHE=memcache
cache:
  directories:
    - vendor
    - glide-$(go version | awk '{ print $NF }' | tr '/' '-')
install:
  - make installdeps
script:
  - make test
